infra:
  log_dir: ./ # where all the experiments are
  exp_name: finetuning # create a subdirectory for each set of experiments
  comment: patient_disc_dev # can use this to customise for each experiment
  seed: 1000

root: "."
out_dir: "FT_DIR"
eval_only:


wandb:
  project: "my_project"
  entity: "my_entity"
  mode: "online"
  use:
  exp_name: "my_exp"


data:
  db_root: F:\Code\datasets\hidisc_data_small
  meta_json: "opensrh.json"
  meta_split_json: "train_val_split.json"
  train_augmentation:
    - which: random_horiz_flip
      params: {}
    - which: random_vert_flip
      params: {}
    - which: gaussian_noise
      params: {}
    - which: color_jitter
      params: {}
    - which: random_autocontrast
      params: {}
    - which: random_solarize
      params:
        threshold: 0.2
    - which: random_sharpness
      params:
        sharpness_factor: 2
    - which: gaussian_blur
      params:
        kernel_size: 5
        sigma: 1
    - which: random_affine
      params:
        degrees: 10
        translate: [0.1, 0.3]
    - which: random_resized_crop
      params:
        size: 300
    - which: random_erasing
      params: {}

  balance_study_per_class: false

model:
  backbone: resnet50
  start_from_ssl_ckpt:
  checkpoints_path: ""
  num_classes: 7
  finetuning: 'linear' # [linear, full]



training:
  batch_size: 128
  num_epochs: 40
  optimizer: sgd # [sgd, adam, adamw]
  learn_rate: 0.1
  scheduler:
    which: cos_warmup
    params:
      num_warmup_steps: 0.1
      num_cycles: 0.5
  imagenet_backbone_checkpoint: null
  eval_ckpt_ep_freq: 5
  train_attack:
  attack_eps: 8.0
  attack_steps: 7

distributed:
  single_gpu:
  world_size: 1
  local_rank: -1
  dist_on_itp: False
  dist_url: "env://"
  find_unused_parameters:
  rank:
  gpu:
  distributed:
  dist_backend:

hydra:
  run:
    dir: ${root}/${out_dir}
  job:
    chdir: True
#    config:
#      override_dirname:
#        kv_sep: "_"
#        item_sep: "_"
#        exclude_keys:
#          - out_dir
#          - root
#          - eval_only
#          - model.restart_from_ckpt
#          - model.name
#          - train.epochs

